const themes = {
    theme1: {
        title: 'black',
        main: "#343a40",
        color1: "#225098",
        color2: "#eb6864",
        text1: "black",
        text2: "white",
        greyedText: "#c7c7c7",
        selected: "lightgrey",
        border1: "black",
        background1: "white",
        background2: "gainsboro",
        background3: "blue",
        image: "https://images.unsplash.com/photo-1578479067625-bf9ac0652ad2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1566&q=80"
    },
    theme2: {
        title: '#b80104',
        main: "black",
        color1: "whitesmoke",
        color2: "white",
        text1: "firebrick",
        text2: "black",
        greyedText: "navy",
        selected: "lightgrey",
        border1: "black",
        background1: "rgba(232, 187, 114, 0.5)",
        background2: "white",
        background3: "oldlace",
        image: "https://images.unsplash.com/photo-1533647326420-d4097513dc42?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1506&q=80"
    },
    theme3: {
        title: 'black',
        main: "beige",
        color1: "aliceblue",
        color2: "azure",
        text1: "darkkhaki",
        text2: "burlywood",
        greyedText: "gainsboro",
        selected: "lightgrey",
        border1: "lightskyblue",
        background1: "oldlace",
        background2: "whitesmoke",
        background3: "#6299af",
        image: "https://images.unsplash.com/photo-1579839783054-b06a3e70f162?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"
    },
    theme4: {
        title: 'black',
        main: "teal",
        color1: "springgreen",
        color2: "turquoise",
        text1: "violet",
        text2: "saddlebrown",
        greyedText: "salmon",
        selected: "lightgrey",
        border1: "palevioletred",
        background1: "palegoldenrod",
        background2: "gainsboro",
        background3: "blue",
        image: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
    },
    theme5: {
        title: 'black',
        main: "lemonchiffon",
        color1: "lawngreen",
        color2: "lavenderblush",
        text1: "indianred",
        text2: "indigo",
        greyedText: "gainsboro",
        selected: "lightgrey",
        border1: "fuchsia",
        background1: "floralwhite",
        background2: "gainsboro",
        background3: "blue",
        image: "https://images.unsplash.com/photo-1482376297902-a54c222cec2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
    },
}

export default themes.theme2;